### PR TITLE
build: bump TRS API specs

### LINKED ISSUE #108: Update trs-specs
Update TRS API Specifications.

### PR DESCRIPTION
**Pull request by kushagra189**
## Description

* Update latest spec versions as defined [here](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/openapi/openapi.yaml).
* Minor tweaks in test cases.
* Current specs do not support security definitions.

Fixes #108 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Maintenance

## Checklist:

- [x] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage
- [x] I have added docstrings following the [Python style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/python.md) of this project to all new modules, classes, methods and functions are documented with docstrings following; I have updated any previously existing docstrings, if applicable
- [x] I have updated any sections of the app's documentation that are affected by the proposed changes, if applicable

### CODE REVIEW

**Review by uniqueg — COMMENTED** [review]
Looks good. But I'm wondering: Don't the updated specs require any changes to the controllers at all?

Also, what exactly do you mean by:
> Current specs do not support security definitions

?

**Comment by kushagra189** [comment]
Oh just that with the current updated specs for `trs-filer`, we have not added the bearer token and other definitions.

**Comment by uniqueg** [comment]
That's fine, we can add them through FOCA, no? If it's not in the specs, it just means we can do what we want :shrug:

**Comment by uniqueg** [comment]
What about changes to controllers? None of the spec changes require behavioral changes?

**Comment by kushagra189** [comment]
> That's fine, we can add them through FOCA, no? If it's not in the specs, it just means we can do what we want 🤷

Yes we can add them via FOCA, we have just comment those specs for now.

**Comment by kushagra189** [comment]
> What about changes to controllers? None of the spec changes require behavioral changes?

Nope, we had the edges covered. Minor change was required in one of the integration test.

**Review by uniqueg — APPROVED** [review]

**Comment by uniqueg** [comment]
Approved!

**Pull request merged**
